/* Copyright (C) 2021  Nikolaj J. Ulrik <nikolaj@njulrik.dk>,
 *                     Simon M. Virenfeldt <simon@simwir.dk>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef VERIFYPN_BITPRODUCTSTATESET_H
#define VERIFYPN_BITPRODUCTSTATESET_H

#include "PetriEngine/Structures/StateSet.h"
#include "LTL/Structures/ProductState.h"

#include <ptrie/ptrie.h>
#include <cstdint>

namespace LTL { namespace Structures {


    /**
     * Bit-hacking product state set for storing pairs (M, q) compactly in 64 bits.
     * Allows for a max of 2^nbits Büchi states and 2^(64-nbits) markings without overflow.
     * @tparam nbits the number of bits to allocate for Büchi state. Defaults to 20-bit. Max is 32-bit.
     */
    using stateid_t = size_t;
    using result_t = std::tuple<bool, stateid_t, size_t>;

    template<typename stateset_type = ptrie::set<stateid_t,17,32,8>, uint8_t nbits = 20>
    class BitProductStateSet {
    public:

        explicit BitProductStateSet(const PetriEngine::PetriNet& net, uint32_t kbound = 0)
                : _markings(net, kbound, net.numberOfPlaces())
        {
        }

        static_assert(nbits <= 32, "Only up to 2^32 Büchi states supported");
        static_assert(sizeof(size_t) >= 8, "Expecting size_t to be at least 8 bytes");

        static size_t get_buchi_state(stateid_t id) { return id & BUCHI_MASK; }

        static size_t get_marking_id(stateid_t id) { return id >> MARKING_SHIFT; }

        static stateid_t get_product_id(size_t markingId, size_t buchiState)
        {
            return (buchiState & BUCHI_MASK) | (markingId << MARKING_SHIFT);
        }

        /**
         * Insert a product state into the state set.
         * @param state the product state to insert.
         * @return tripple of [success, ID, data_id] where data_id can be used
         *         for quick-access via get_data (constant-time lookup).
         */
        result_t add(const LTL::Structures::ProductState &state)
        {
            ++_discovered;
            const auto res = _markings.add(state);
            if (res.second == std::numeric_limits<size_t>::max()) {
                return {res.first, res.second, res.second};
            }
            const stateid_t product_id = get_product_id(res.second, state.get_buchi_state());
            assert(res.second == get_marking_id(product_id));
            assert(state.get_buchi_state() == get_buchi_state(product_id));
            auto [is_new, data_id] = _states.insert(product_id);
            return {is_new, product_id, data_id};
        }

        /**
         * Gets the associated data of a data_id, constants-time
         * @param data_id
         * @return the data-object pointed to by data_id (obtained by the add() method).
         */
        auto& get_data(size_t data_id) {
            return _states.get_data(data_id);
        }

        /**
         * Retrieve a product state from the state set.
         * @param id Composite state ID as previously generated by this.
         * @param state Output parameter to write product state to.
         * @return true if the state was successfully retrieved, false otherwise.
         */
        virtual void decode(LTL::Structures::ProductState &state, stateid_t id)
        {
            assert(_states.exists(id).first);
            auto marking_id = get_marking_id(id);
            auto buchi_state = get_buchi_state(id);
            _markings.decode(state, marking_id);
            state.set_buchi_state(buchi_state);
        }

        size_t discovered() const { return _discovered; }

        size_t max_tokens() const { return _markings.maxTokens(); }

    protected:

        static constexpr auto BUCHI_MASK = ~(std::numeric_limits<size_t>::max() << (nbits));
        static constexpr auto MARKING_SHIFT = nbits;

        PetriEngine::Structures::StateSet _markings;
        stateset_type _states;
        static constexpr auto _err_val = std::make_pair(false, std::numeric_limits<size_t>::max());

        size_t _discovered = 0;
    };

    template<uint8_t nbits = 20>
    class TraceableBitProductStateSet : public BitProductStateSet<ptrie::map<stateid_t,std::pair<size_t,size_t>>, nbits> {
    public:
        explicit TraceableBitProductStateSet(const PetriEngine::PetriNet& net, uint32_t kbound = 0)
                : BitProductStateSet<ptrie::map<stateid_t,std::pair<size_t,size_t>>,nbits>(net, kbound)
        {
        }

        void decode(ProductState &state, stateid_t id) override
        {
            _parent = id;
            BitProductStateSet<ptrie::map<stateid_t,std::pair<size_t,size_t>>,nbits>::decode(state, id);
        }

        void set_history(stateid_t id, size_t transition)
        {
            assert(this->_states.exists(id).first);
            this->_states[id] = {_parent, transition};
        }

        std::pair<size_t, size_t> get_history(stateid_t stateid)
        {
            assert(this->_states.exists(stateid).first);
            return this->_states[stateid];
        }

    private:
        stateid_t _parent = 0;
    };
} }

#endif //VERIFYPN_BITPRODUCTSTATESET_H
